# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.0
    hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    - id: terraform_validate
    - id: terraform_tfsec
      args:
        - --args=--minimum-severity=MEDIUM
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-yaml
        args: ['--unsafe']  # Allow custom YAML tags
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: end-of-file-fixer
      - id: mixed-line-ending
  # - repo: git://github.com/ansible-community/ansible-lint
  #   rev: v5.3.2
  #   hooks:
  #     - id: ansible-lint
  # - repo: git://github.com/markdownlint/markdownlint
  #   rev: v0.9.0
  #   hooks:
  #     - id: markdownlint